add methods for adding metadata and mediafiles to entity
inuits/elody-python-sdk pull request #6
Opened 2023-08-23 10:34 UTC by pavelToman

2023-08-25 12:49 UTC, gverm requested changes

2023-08-25 12:49 UTC, gverm commented on src/elody/client.py
> +    def add_object_metadata(self, collection, identifier, payload):
Can you sort the functions in this file? (leave private functions with __ or _ on top)

2023-08-25 12:49 UTC, gverm commented on src/elody/client.py
> +                response.json()["message"].endswith("has no metadata")
The parentheses are superfluous. Can you remove them and format the file with Black?

2023-08-25 12:49 UTC, gverm commented on src/elody/client.py
> +            return self.__handle_response(response, "Failed to add matadata")
Typo "matadata" -> "metadata"

2023-08-25 12:49 UTC, gverm commented on src/elody/client.py
> +            return self.__handle_response(response, "Failed to add matadata")
Ditto.

2023-08-25 12:49 UTC, gverm commented on src/elody/client.py
> +    def add_entity_mediafiles(self, identifier,  payload):
Too many spaces between identifier and payload.

2023-08-25 13:24 UTC, gverm requested changes
Can you sort the functions alphabetically (sorry should have been a bit clearer about that before)?

Also remove the newline between the two imports at the top.

2023-09-04 07:32 UTC, gverm commented
@pavelToman Can you squash these commits and make sure to add the authorship info is correct? Make sure that `git log` shows your full name + Inuits email address. Also make sure that your Inuits email address is linked to your GitHub profile.

2023-09-08 10:47 UTC, pavelToman commented
I connect my github with an inuits email but the squash should be made by you during the merge I think?

2023-09-08 12:21 UTC, merged